name: Simple CI/CD for HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check HTML
      uses: reviewdog/action-htmlhint@v1
      with:
        reporter: github-pr-check

  deploy:
    needs: lint-html
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
